In [ ]:
#Importing Libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
import warnings
import sklearn.exceptions
warnings.filterwarnings("ignore", category=sklearn.exceptions.UndefinedMetricWarning)

#Importing the Dataset

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)

In [ ]:
#Preprocessing
X = irisdata.drop('Class', axis=1)
y = irisdata['Class']

#Train Test Split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [ ]:
#Training the Algorithm

#1. Polynomial Kernel
#In the case of polynomial kernel, 
#you also have to pass a value for the degree parameter of the SVC class. 
#This basically is the degree of the polynomial.

svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

#Making Predictions

y_pred = svclassifier.predict(X_test)

#Evaluating the Algorithm

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))



[[13  0  0]
 [ 0 11  2]
 [ 0  0  4]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      0.85      0.92        13
 Iris-virginica       0.67      1.00      0.80         4

       accuracy                           0.93        30
      macro avg       0.89      0.95      0.91        30
   weighted avg       0.96      0.93      0.94        30



In [ ]:
#2. Gaussian Kernel

#To use Gaussian kernel, 
#you have to specify 'rbf' as value for the Kernel parameter of the SVC class.

svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

#Making Predictions

y_pred = svclassifier.predict(X_test)

#Evaluating the Algorithm

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[13  0  0]
 [ 0 11  2]
 [ 0  0  4]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      0.85      0.92        13
 Iris-virginica       0.67      1.00      0.80         4

       accuracy                           0.93        30
      macro avg       0.89      0.95      0.91        30
   weighted avg       0.96      0.93      0.94        30



In [ ]:
#3. Sigmoid Kernel

svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

#Making Predictions

y_pred = svclassifier.predict(X_test)

#Evaluating the Algorithm

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 0  0 13]
 [ 0  0 13]
 [ 0  0  4]]
                 precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00        13
Iris-versicolor       0.00      0.00      0.00        13
 Iris-virginica       0.13      1.00      0.24         4

       accuracy                           0.13        30
      macro avg       0.04      0.33      0.08        30
   weighted avg       0.02      0.13      0.03        30

